import tailwindcssAnimate from "tailwindcss-animate"
import withMT from "@material-tailwind/react/utils/withMT"
 
module.exports = withMT({
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
			backgroundImage: {
  			'layout-pattern': "url('/portada con logo chico.png')",
				'fondo-tres': "url('/fondo.png')",
				'fondo-olas-celestes': "url('/olaCeleste.png')",
				'hora-de-viajar-neuquen': "url('/horadeviajarneuquen.png')",
				'hora-de-viajar-mundo': "url('/horadeviajarmundo.png')",
				'hora-de-viajar-norte': "url('/horadeviajarnorte.png')",
				'hora-de-viajar-sur': "url('/horadeviajarsur.png')"
  		},
			colors: {
  			'dos-puntos-brown-light': '#EBCD92',
  			'dos-puntos-yellow': '#DD9C2C',
  			'dos-puntos-pink': '#B13463',
  			'dos-puntos-gray': '#1C2544',
			'dos-puntos-blue': '#55B6C6',
			"error": "#ba1a1a",
                        "tertiary-container": "#55b6c6",
                        "on-primary-fixed-variant": "#624000",
                        "tertiary-fixed": "#9bf0ff",
                        "on-secondary-container": "#535c7e",
                        "on-surface-variant": "#514535",
                        "secondary": "#545d7f",
                        "primary": "#815600",
                        "on-error-container": "#93000a",
                        "inverse-surface": "#3f2e02",
                        "outline-variant": "#d5c4af",
                        "tertiary": "#006875",
                        "on-secondary": "#ffffff",
                        "on-primary-fixed": "#291800",
                        "primary-container": "#dd9c2c",
                        "inverse-primary": "#ffba49",
                        "background": "#fff8f2",
                        "on-tertiary-fixed": "#001f24",
                        "surface-container-high": "#ffe5b5",
                        "on-tertiary": "#ffffff",
                        "tertiary-fixed-dim": "#75d4e5",
                        "on-secondary-fixed-variant": "#3d4566",
                        "surface-variant": "#fedfa2",
                        "on-primary-container": "#553700",
                        "surface-dim": "#f5d69b",
                        "surface-tint": "#815600",
                        "secondary-container": "#cdd6fe",
                        "primary-fixed": "#ffddb1",
                        "on-primary": "#ffffff",
                        "secondary-fixed-dim": "#bcc5ec",
                        "on-secondary-fixed": "#101a38",
                        "outline": "#837563",
                        "inverse-on-surface": "#ffefd4",
                        "surface-container-lowest": "#ffffff",
                        "on-tertiary-fixed-variant": "#004f58",
                        "surface-bright": "#fff8f2",
                        "primary-fixed-dim": "#ffba49",
                        "secondary-fixed": "#dce1ff",
                        "on-error": "#ffffff",
                        "surface-container": "#ffecca",
                        "on-tertiary-container": "#00454d",
                        "surface": "#fff8f2",
                        "on-background": "#261a00",
                        "surface-container-highest": "#fedfa2",
                        "on-surface": "#261a00",
                        "surface-container-low": "#fff2de",
                        "error-container": "#ffdad6"
			},
			"borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "stack-md": "16px",
                        "stack-xl": "64px",
                        "gutter": "24px",
                        "stack-lg": "32px",
                        "margin-desktop": "48px",
                        "stack-sm": "8px",
                        "unit": "8px",
                        "stack-xs": "4px",
                        "margin-mobile": "16px",
                        "container-max": "1280px"
                    },
                    "fontFamily": {
                        "headline-lg": ["Noto Serif"],
                        "body-lg": ["Noto Serif"],
                        "body-md": ["Noto Serif"],
                        "label-sm": ["Noto Serif"],
                        "label-md": ["Noto Serif"],
                        "display-lg": ["Noto Serif"],
                        "headline-md": ["Noto Serif"],
                        "display-lg-mobile": ["Noto Serif"]
                    },
                    "fontSize": {
                        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "500"}],
                        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                        "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
                    }
		},
  },
  plugins: [tailwindcssAnimate],
});