import type { Metadata } from "next";
import 'keen-slider/keen-slider.min.css'
import "./globals.css";


export const metadata: Metadata = {
  title: "Dos Puntos Turismo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
